### PR TITLE
Add a contact form to my portfolio.

### PR DESCRIPTION
**Pull request by Ouail-01**
> ### In this pull request, I added a contact form and finish the mobile version.

# Learning objectives :
- Create forms with HTML5 validations.
- Understand the importance of UX.
- Understand how to parse a Figma design to create a UI.

### CODE REVIEW

**Review by Debas-31 — APPROVED** [review]
> ## Hi  @Ouail-01 and  @yaredtt  :wave:, 

# Status: Approved :heavy_check_mark:  :heavy_check_mark:  :heavy_check_mark: 

Your project is complete !  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



## Highlights

- Linters setup :heavy_check_mark:
- GitHub flow :heavy_check_mark: 
- PR title and summary :heavy_check_mark: 
- Commit message :heavy_check_mark:
- UI design :heavy_check_mark: 
- Project functionality :heavy_check_mark: 
- Figma template usage :heavy_check_mark: 


## Optional suggestions
- [OPTIONAL] - Kindly add the project name and feature section in your README file with your list of features in the project milestone.

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by Reggeditt — COMMENTED** [review]
Congrats!! theres nothing more to say than Great Job! 
giphy

**Review by Chaseknis — COMMENTED** [review]
### Congratulations Your project is complete! There is nothing else to say.🍾 



### Highlights

- Great Use of HTML semantics ✅ 
- No linter Errors ✅ 
- UI design  ✅ 
- Figma template usage ✅

**Review by HanaSabih — COMMENTED** [review]
Used proper HML Semantics ✅
No linter errors ✅
Aligned images correctly ✅
Used Figma Templates ✅
##Congratulations Again 🥳

**Pull request merged**
